name: manakmishra
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.2.0
  sizer: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Chivo
      fonts:
        - asset: assets/fonts/Chivo/Chivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Chivo/Chivo-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
